const aboutInformation01 = `Sou um desenvolvedor apaixonado por segurança, inteligência artificial e tecnologia em geral. Minha história começa na infância, quando descobri minha paixão pelos jogos e, especialmente, pela área de segurança.`;
const aboutInformation02 = `Com esse interesse em mente, decidi ingressar no curso de Bacharel em Ciência da Computação, onde pude aprofundar meus conhecimentos sobre a segurança da informação. Foi nessa época que eu realizei minha monografia sobre políticas de segurança para startups, tema que me permitiu explorar as possibilidades de proteção dos dados em empresas de pequeno porte.`;
const aboutInformation03 = `Após a graduação, decidi realizar um MBA em Gestão Empresarial, com o objetivo de aprimorar minhas habilidades empreendedoras. No entanto, ainda motivado pela paixão pela segurança, decidi prestar concursos para a área de segurança pública, mas infelizmente não fui aprovado.`;
const aboutInformation04 = `Apesar da frustração, não desisti do meu sonho de servir à área de segurança. Em vez disso, decidi ingressar na área de segurança privada de uma transportadora multinacional, onde pude me desenvolver profissionalmente e exercer diversas funções, incluindo liderança no setor de manutenção e instalação de cofres eletrônicos. `;
const aboutInformation05 = `Com o objetivo de seguir minha verdadeira vocação, comecei minha transição de carreira em fevereiro de 2022. Depois de ser aprovado no processo seletivo da Trybe, pedi demissão e mergulhei de corpo e alma nessa nova jornada.`;
const aboutInformation06 = `Minha experiência na área de segurança me proporcionou uma descoberta valiosa: tenho uma paixão anormal por resolver problemas, independentemente da complexidade.`;
const aboutInformation07 = `Com o passar do tempo, percebi que a resolução de problemas é uma habilidade crucial para a carreira de um desenvolvedor. É preciso estar sempre pronto para enfrentar novos desafios e encontrar soluções inovadoras para os problemas que surgem. E é exatamente isso que me motiva a trabalhar na área de tecnologia.`;
const aboutInformation08 = `Além disso, minha experiência na área de segurança me ensinou a importância de considerar a segurança em todas as etapas do desenvolvimento de software. É crucial garantir a segurança dos dados e sistemas, desde a concepção do projeto até a implementação e manutenção.`;
const aboutInformation09 = `Por essas razões, estou sempre em busca de aprimoramento e aprendizado contínuo, para me manter atualizado com as tendências e as melhores práticas da indústria de tecnologia. E isso se reflete no meu trabalho diário, onde procuro entregar soluções inovadoras, seguras e de alta qualidade para os meus clientes e usuários.`;

export { aboutInformation01, aboutInformation02, aboutInformation03, aboutInformation04, aboutInformation05, aboutInformation06, aboutInformation07, aboutInformation08, aboutInformation09 };
