const academicInfo01 = `Formação de profissionais para atuar nas áreas mais tradicionais da informática, como banco de dados, programação, redes de computadores e engenharia de software.`;
const academicInfo02 = `Obtenção de conhecimentos para implementar soluções inovadoras no contexto da Indústria 4.0, por meio de tecnologias como inteligência artificial, internet das coisas, realidade virtual e aumentada, big data, ciência de dados e machine learning, apoiando o processo de transformação digital das organizações.`;
const academicInfo03 = `Utilização de metodologias ativas de aprendizagem, objetivando gerar um entendimento mais profundo dos tópicos em contextos reais e práticos, como aprendizagem baseada em problema, aprendizagem baseada em times, aprendizagem baseada em projetos, sala de aula invertida, gamificação, blended learning e dinâmicas ativas de aprendizagem.`;

const academicInfo04 = `MBA que aprofunda os aspectos-chave da gestão empresarial, desenvolvendo competências práticas de gerenciamento e tomada de decisão em negócios.`;
const academicInfo05 = `Abrange áreas como estratégia, planejamento, finanças, custos, produção, processos, marketing, vendas, tributos, entre outras, proporcionando uma visão ampla e moderna da gestão empresarial com foco em resultados e equilíbrio financeiro.`;
const academicInfo06 = `Permite o desenvolvimento de habilidades necessárias para a tomada de decisões eficazes, estimulando a reflexão, a troca de experiências e a ação empresarial estratégica para análise e compreensão de mudanças e soluções no mundo dos negócios.`;

const academicInfo07 = `A Trybe é uma escola de tecnologia que oferece um programa de formação em desenvolvimento web e habilidades comportamentais para formar profissionais preparados para atuar no mercado de trabalho atual. O programa é dividido em quatro módulos: Fundamentos, Front-end, Back-end e Ciência da Computação, com uma carga horária de mais de 1.500 horas de aulas ao vivo e conteúdo interativo online.`;
const academicInfo08 = `Além do conteúdo técnico, a Trybe enfatiza o desenvolvimento de habilidades comportamentais, como trabalho em equipe, comunicação, liderança e gestão de projetos, com o objetivo de formar profissionais completos e preparados para enfrentar os desafios do mercado de trabalho.`;
const academicInfo09 = `A escola conta com uma metodologia de ensino prática, que busca simular o ambiente de trabalho real, com projetos individuais e em equipe, feedback constante dos mentores e a possibilidade de trabalhar em projetos reais.`;
const academicInfo10 = `A Trybe tem uma taxa de contratação de mais de 90% dos alunos formados, com parcerias em empresas renomadas do mercado de tecnologia. Além disso, a escola oferece suporte de carreira, como mentoria individualizada, preparação para entrevistas e conexão com empresas do mercado. Ser um aluno ou ex-aluno da Trybe pode ser um grande diferencial no mercado de trabalho de tecnologia.`;

export { academicInfo01, academicInfo02, academicInfo03, academicInfo04, academicInfo05, academicInfo06, academicInfo07, academicInfo08, academicInfo09, academicInfo10 };